function [sensorData, config] = format_lidar_RFS(z_t, x_t, t, lidar_range)
    ptCloud = [z_t.Cartesian+[x_t(1) x_t(2)] zeros(size(z_t.Cartesian,1),1)];
    sensorData = struct('Time',t, ...
        'SensorIndex',1, ...
        'Measurement',ptCloud', ...
        'MeasurementParameters',struct ...
        );
    params(1) = struct("Frame","Spherical", ...
        "OriginPosition",[x_t(1);x_t(2);0], ...
        "OriginVelocity",[0;0;0], ...
        "Orientation",eye(3), ...
        "HasRange",true, ...
        "HasVelocity",false);
    params(2) = struct("Frame","Rectangular", ...
        "OriginPosition",[0;0;0], ...
        "OriginVelocity",[0;0;0], ...
        "Orientation",eye(3), ...
        "HasRange",true, ...
        "HasVelocity",true);
    config = trackingSensorConfiguration(1, ...
        'SensorLimits',[-180 180;0 lidar_range], ...
        'SensorTransformParameters',struct, ...
        'IsValidTime',true, ...
        'SensorTransformParameters',params);
end